version: 2.1
jobs:
  build:
    docker:
      - image: cimg/go:1.14
    steps:
      - checkout
      - run: make test
  benchmark:
    docker:
      - image: cimg/go:1.14
    steps:
      - checkout
      - run: make benchmark
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - benchmark